apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: ARTIFACTID
  namespace: cpu
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: citizen-service
    apps.tanzu.vmware.com/has-tests: "false"
    apps.tanzu.vmware.com/auto-configure-actuators: "false"
spec:
  build:
    env:
      - name: BP_JVM_VERSION
        value: "17"
  params:
    - name: annotations
      value:
        autoscaling.knative.dev/minScale: "1"
    - name: gitops_server_address
      value: https://github.com/
    - name: gitops_repository_owner
      value: cpulcini2003
    - name: gitops_repository_name
      value: config-repo
    - name: gitops_ssh_secret
      value: git-secret
    - name: git_user_email
      value: cpulcini2003@gmail.com
    - name: git_user_name
      value: cpulcini2003
  source:
    git:
      url: <https URL for your generated project's Git repository>
      ref:
        branch: main
  ##BINDING_OPTION
